metadata {
  id {
    package: "com.example"
    name: "feature_detector"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "A ROS service that detects AR marker tags."
  }
  display_name: "Feature Detector Service (ROS)"
}
service_def {
  real_spec {
    image {
      archive_filename: "feature_detector.tar"
    }
  }
  sim_spec {
    image {
      archive_filename: "feature_detector.tar"
    }
  }
}
assets {
  default_configuration_filename: "default_config.binarypb",
  parameter_descriptor_filename: "parameter-descriptor-set.proto.bin",
  image_filenames: ["feature_detector.tar"]
}
