metadata {
  id {
    package: "com.example"
    name: "listener_service"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "A ROS listener service that subscribes to a ROS topic."
  }
  display_name: "Listener Service (ROS)"
}
service_def {
  real_spec {
    image {
      archive_filename: "listener_service.tar"
    }
  }
  sim_spec {
    image {
      archive_filename: "listener_service.tar"
    }
  }
}
assets {
  default_configuration_filename: "default_config.binarypb",
  parameter_descriptor_filename: "parameter-descriptor-set.proto.bin",
  image_filenames: ["listener_service.tar"]
}
